### ISSUE TITLE
Gunakan StyleCI untuk menyesuaikan style script secara otomatis

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3318]
### Bagaimana alurnya sampai muncul masalah?
Saat ini pemeriksaan script sudah sesuai dengan style guide OpenSID di https://github.com/OpenSID/OpenSID/wiki/Aturan-Penulisan-Script dilakukan secara manual, sehingga banyak yg terlewat.

### Seperti apa yang diharapkan?
Pemeriksaan dan penyesuaian penulisan script dilakukan secara otomatis. Alat bantu https://docs.styleci.io/ atau lainnya sepertinya dapat digunakan untuk keperluan ini. Syaratnya adalah aturan penulisan script OpenSID dapat dipasang di alat bantu ybs.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.07
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Pak @esyede mungkin bisa bantu???

**Comment by esyede** [comment]
Rule-set opensid seperti apa?
Folder dan file yang perlu di-exclude apa saja?

Dan kalau bisa dibikinkan branch tersendiri untuk testingnya karena kelihatannya agak risky.

Sementara saya buat seperti ini:
```yml
preset: psr2
risky: false
finder:
  exclude:
    - assets/filemanager
    - logs
    - securimage
    - system
    - vendor
  name: "*.php"
  not-name:
    - 'index.php'

```
