### ISSUE TITLE
Permintaan fitur: Docker Container

### ISSUE THREAD

**Issue by agung2001** [OpenSID/OpenSID#8591]
### Apa kekurangan yg ingin diatasi?

Mengembangkan fitur Docker container menjadi penting bagi pengembangan OpenSID karena beberapa alasan, yaitu: 

1. Konsistensi Lingkungan
OpenSID menggunakan banyak extensi sebagai syarat mutlak installasi aplikasi. Docker memungkinkan pengembang untuk membuat lingkungan pengembangan yang konsisten di berbagai sistem. Tanpa Docker, setiap pengembang atau admin server mungkin harus mengonfigurasi manual sistem operasi, dependensi, dan versi library, yang bisa menimbulkan masalah **ketidakcocokan**. Dengan Docker, OpenSID dapat berjalan dalam “container” yang memiliki semua konfigurasi yang sama, sehingga mengurangi risiko bug yang disebabkan oleh perbedaan lingkungan.

![](https://panduan.opendesa.id/opensid/cek-syarat2.png)

2. Isolasi Aplikasi
Docker menyediakan isolasi yang kuat. Setiap container berjalan secara independen dan tidak mempengaruhi sistem host. Ini memberikan keuntungan bagi OpenSID, di mana pengembangan fitur atau update bisa diuji tanpa merusak instalasi yang sudah ada, serta memudahkan rollback jika terjadi masalah.

3. Pengembangan dan Kolaborasi Lebih Cepat
Dengan Docker, pengembang OpenSID dapat dengan cepat membuat atau mereset lingkungan pengembangan mereka, memungkinkan kolaborasi yang lebih cepat dan produktif antar anggota tim. Setiap orang bisa menggunakan container yang sama, memastikan tidak ada perbedaan konfigurasi yang menyebabkan bug sulit direplikasi atau diperbaiki.

Kesimpulan
Fitur Docker container untuk OpenSID akan membantu meningkatkan keandalan, konsistensi, dan efisiensi pengembangan serta manajemen sistem yang pada akhirnya akan membuat OpenSID lebih mudah digunakan dan dikembangkan di berbagai lingkungan dan oleh berbagai pihak.

### Jelaskan solusi yg diinginkan

Saya telah melakukan uji coba dengan menggunakan konfigurasi docker container sebagai berikut :

<details><summary>Dockerfile</summary>

```
# Gunakan container PHP dan Apache dengan versi 8.1.30
FROM php:8.1.30-apache

# Instal dependensi sistem dan ekstensi PHP
# gd: Memerlukan libpng-dev, libjpeg-dev, libfreetype6-dev
# tidy: Memerlukan libzip-dev, libtidy-dev
# zip: Memerlukan libzip-dev
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    libtidy-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) \
        gd \
        exif \
        mysqli \
        pdo \
        pdo_mysql \
        tidy \
        zip

# Mengatur direktori kerja
WORKDIR /var/www/html

# Mengekspos port 80 untuk Apache
EXPOSE 80

# Start Apache
CMD ["apache2-foreground"]
```

</details>

<details><summary>docker-compose.yml</summary>

```
version: '3.8'

services:

  # Layanan Web
  web:
    image: opendesa:latest
    container_name: opendesa_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ${PWD}:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  # Layanan Database
  db:
    image: mysql:8.0
    container_name: opendesa_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: opendesa
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
```
</details>

dan hasilnya adalah sebagai berikut : 

<details><summary>Persyaratan Server / Ekstensi PHP</summary>

<img width="1040" alt="Screenshot 2024-10-15 at 20 08 15" src="https://github.com/user-attachments/assets/baa7855f-cbce-42bc-9431-b19bd3ca8b79">
</details>

<details><summary>Pengaturan Database</summary>

<img width="1039" alt="Screenshot 2024-10-15 at 20 09 02" src="https://github.com/user-attachments/assets/21a18042-96d6-4932-8345-fbbe82dedc7a">

<img width="1039" alt="Screenshot 2024-10-15 at 20 09 20" src="https://github.com/user-attachments/assets/1ac281dd-6d6f-4c36-9063-2b2d8c38f6a6">
</details>

dengan hanya:
- menambahkan 2 file saja `Dockerfile` dan `docker-compose.yml`
- lalu menjalankan perintah `docker-compose up --build`

kita dapat menginstall semua extensi php beserta dengan databasenya dengan hitungan detik di lokal komputer kita
hal ini dapat membantu meningkatkan waktu pengembangan projek OpenSID

anda dapat melakukan uji coba mandiri disini : https://github.com/agung2001/OpenSID/tree/docker
1. Clone repo pada branch `docker`
2. Lalu jalankan perintah `docker-compose up --build`

### Apakah ada alternatif lain

kita dapat menggunakan virtual mesin untuk menggantikan peran docker container
akan tetapi proses nya tetap saja rumit, dan juga memakan sumber komputasi yang besar
untuk saat ini docker adalah satu satunya pilihan yang murah dan mudah digunakan

### Untuk versi OpenSID mana

Rilis v2410.0.0
